Codefirstapproach/Controllers/HomeController.cs
using Codefirstapproach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Codefirstapproach.Controllers
{
    public class HomeController : Controller
    {
        Codefirst db = new Codefirst();
        public ActionResult Index()
        {
            var userInCookie = Request.Cookies["AccountInfo"];
            if (userInCookie != null)
            {

                var std = GetPersonalinfos();
                var tchr = GetEducations();

                var edu = GetWorkexperience();
                var sk = GetSkill();

                MultiModel data = new MultiModel();
                data.My_personalinfo = std;
                data.My_education = tchr;
                data.My_workexperience = edu;
                data.My_skill = sk;

                return View(data);


            }
            else
            {

                return RedirectToAction("Login", "Account");

            }
        }

        public personalinfo GetPersonalinfos()
        {
            
            return db.personalinfos.ToList()
                .OrderByDescending(q => q.pid).FirstOrDefault();
        }
        public education GetEducations()
        {

            return db.educations.ToList().OrderByDescending(q => q.eduid).FirstOrDefault();
        }

        public workexperience GetWorkexperience()
        {

            return db.workexperiences.ToList()
                .OrderByDescending(q => q.workid).FirstOrDefault();
        }
        public skill GetSkill()
        {

            return db.skills.ToList().OrderByDescending(q => q.skillid).FirstOrDefault();
            

        }
       
        public ActionResult Dashboard()
        {
            return View();
           
        }

    }
}

Codefirstapproach/Controllers/personalinfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Codefirstapproach.Models;

namespace Codefirstapproach.Controllers
{
    public class personalinfoesController : Controller
    {
        private Codefirst db = new Codefirst();

        // GET: personalinfoes
      

        // GET: personalinfoes/Create
        public ActionResult Create()
        {
            var userInCookie = Request.Cookies["AccountInfo"];
            if (userInCookie != null)
            {
                ViewBag.userid = new SelectList(db.users, "userid", "username");
                return View();

            }
            else
            {

                return RedirectToAction("Login", "Account");

            }
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(personalinfo personal)
        {
            if (ModelState.IsValid)
            {
                var userInCookie = Request.Cookies["AccountInfo"];
                int User_id;
                User_id = Convert.ToInt32(userInCookie["idUser"]);
               
                personal.userid = User_id;
                
                db.personalinfos.Add(personal);
                db.SaveChanges();
                return RedirectToAction("Create","educations");
            }

              return View();
        }

        // GET: personalinfoes/Edit/5
     

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Codefirstapproach/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
<head>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

</head>

<body style="background-color:burlywood">

    <div class="jumbotron">
        <center><h3>Welcome your are loogedin</h3></center>
        <center><h3>@Html.ActionLink("lets build your Cv", "Create", "personalinfoes")</h3></center>
    </div>
    </body>

Codefirstapproach/Views/Home/Index.cshtml
@using Codefirstapproach.Models
@model MultiModel
@{
    Layout = null;
}



<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/996973c893.js"></script>

    <!-- Style -->
    @*<link rel="stylesheet" href="style.css" />*@
    <link href="~/Content/style.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,700,800,900&display=swap"
          rel="stylesheet" />

    <title>Resume</title>
</head>
<body>
    <div class="box">
        <div class="header">
            <div class="header-left">
                <div class="name">
                    <h1 class="first-name"><b>CV</b></h1>
                    <h1 class="last-name">Builder</h1>
                </div>
            </div>

        </div>
        <hr />

        <div class="skills">
            <div class="skills-heading grey">
                <i class="fas fa-bullseye icon"></i>
                <h2>PersonalInfo</h2>
            </div>

            <ul>


                <li>@Model.My_personalinfo.fname</li>
                <li>@Model.My_personalinfo.date_birth</li>
                <li>@Model.My_personalinfo.address</li>
                <li>@Model.My_personalinfo.nationality</li>
                <li>@Model.My_personalinfo.phone</li>
                <li>@Model.My_personalinfo.email</li>
            </ul>
        </div>
        <div class="education">
            <div class="ed-heading grey">
                <i class="fas fa-school icon"></i>
                <h2>Education</h2>
            </div>

            <table>
                <tr>
                    <th> Institute   </th>
                    <th> Title  </th>
                    <th> Degree   </th>
                    <th> Start Date  </th>
                    <th> End Date   </th>
                    <th> Address </th>


                </tr>
                <tr>
                    <td>@Model.My_education.institute</td>

                    <td>@Model.My_education.title</td>
                    <td>@Model.My_education.degree</td>
                    <td>@Model.My_education.start_date</td>
                    <td>@Model.My_education.end_date</td>
                    <td>@Model.My_education.address</td>

                </tr>

            </table>
        </div>
        <div class="skills">
            <div class="skills-heading grey">
                <i class="fas fa-tools icon"></i>
                <h2>Skills</h2>
            </div>

            <ul>
                <li>@Model.My_skill.skil</li>

            </ul>
        </div>

        <div class="skills">
            <div class="skills-heading grey">
                <i class="fab fa-creative-commons-nd icon"></i>
                <h2>WorkExperince</h2>
            </div>

            <ul>

                <li>@Model.My_workexperience.company_name</li>
                <li>@Model.My_workexperience.title</li>
                <li>@Model.My_workexperience.countary</li>
                <li>@Model.My_workexperience.start_date</li>
                <li>@Model.My_workexperience.end_date</>
                <li>@Model.My_workexperience.description</li>




            </ul>
        </div>

    </div>
    <div style="margin-top:25px">
        <center> <h2> @Html.ActionLink("lets build your Cv", "Create", "personalinfoes")</h2></center>
    </div>
</body>
</html>